process.env.HISTORY_AUTO_RESTORE = 'false';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
process.env.DATABASE_URL = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'activity-')), 'test.db');
const { sqlite } = require('../src/db/client.ts');
const { upsertBook, markBooksOutsideCurrentWishlistsInactive } = require('../src/services/bookService.ts');
const { upsertWishlist, linkBookToWishlist, reconcileWishlist } = require('../src/services/wishlistService.ts');
const { createPriceSnapshot } = require('../src/services/priceSnapshotService.ts');
const { getDealRankingByWishlist } = require('../src/services/rankingService.ts');
const { getAllBooksPriceHistory } = require('../src/services/reportService.ts');
test('membership removal and seven-day expiry preserve history and last-seen dates', async () => {
  const bookId = await upsertBook({ title: 'A', author: null, productUrl: 'a', imageUrl: null });
  const a = await upsertWishlist({ name:'A', url:'a' }), b = await upsertWishlist({ name:'B', url:'b' });
  await linkBookToWishlist(a, bookId); await linkBookToWishlist(b, bookId);
  await createPriceSnapshot({ bookId, listPrice:200, discountedPrice:100, discountPercent:50, currency:'MXN' });
  await reconcileWishlist(a, []);
  assert.equal((await getDealRankingByWishlist(a)).length, 0);
  assert.equal((await getDealRankingByWishlist(b)).length, 1);
  sqlite.prepare("UPDATE books SET last_seen_at = datetime('now', '-7 days')").run();
  assert.equal((await getDealRankingByWishlist(b)).length, 0);
  const before=sqlite.prepare('SELECT last_seen_at FROM books').get().last_seen_at;
  await markBooksOutsideCurrentWishlistsInactive([]);
  assert.equal(sqlite.prepare('SELECT last_seen_at FROM books').get().last_seen_at,before);
  const history=await getAllBooksPriceHistory();
  assert.equal(history.length,1); assert.equal(history[0].isActive,false);
  await upsertBook({ title:'A', author:null, productUrl:'a', imageUrl:null });
  await linkBookToWishlist(a,bookId);
  assert.equal((await getDealRankingByWishlist(a)).length,1);
});
